source 'https://rubygems.org'
ruby '2.1.2'

gem 'tilt', git: 'git://github.com/rtomayko/tilt.git'
gem 'sinatra', '1.3.2'
gem 'thin'
gem 'haml'
gem 'redcarpet'
gem 'compass'
gem 'coderay'
gem 'deckrb', '>=0.3.0'
gem 'pg'
gem 'sequel'
